// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addbasebooktorentalforeaseofuse2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbasebooktorentalforeaseofuse2));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021258510_add-basebook-to-rental-for-ease-of-use2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
